@startuml FilaInterna/Aluno
    package Domain.DataManegement{
        class FilaInterna {
            - aluno: Aluno[] = []
            - QuantMax: number
            + adicionarAluno(aluno: Aluno): void
            + removerAluno(): Aluno
            + verificarOcupação(): boolean
            + VerificarSeTemAlguem(): boolean
            + tamanhoFila(): Aluno[]
        }

        FilaInterna "1" *-- "0..*" Aluno : contém
    }
@enduml
