@startuml FilaInterna/Aluno

    class MaquinaEventos{
        - eventos: Eventos[] = []
        - instanteDeSimulacao = 0
        + processarEventos()
        + adicionarEvento(novoEvento:Evento)
        # atualizarInstanteDeSimulacao(novoInstanteDeSimulacao:number)
    }

@enduml